name: ite_store
description: ITE Store - Final Exam Flutter Project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # HTTP requests
  http: ^1.2.0
  # Dependency injection
  get_it: ^7.6.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
